### ISSUE TITLE
Question about using your tool and understanding the generated files

### ISSUE THREAD

**Issue by katyukuki** [tfernd/ortho-lora#2]
Hello,
I had the opportunity to use your tool and I really like it, it quickly became my favorite. I have a question regarding its usage. After generating a model and Lora, a txt file is created. Is it correct to understand that if I use the values written in this file as weights solely with Lora, I would be able to replicate the original model's features? I tried merging five models and found that even though the models are different, they had exactly the same weights. In such a case, how can I replicate the original models’ features? Thank you for your time.

**Comment by tfernd** [comment]
Yes, the txt files give you a set of directions for each LoRA to reproduce, as best as possible, the original models.

The weights should be different, are they all 1 or -1?

**Comment by katyukuki** [comment]
Thank you for letting me know. Regarding the weights, they were as follows. After merging the five models, the results are shown below. Notably, "wd-v1-3-full:" and "SweetParfait:" had weights that were exactly the same.
v1-5-pruned: <lora:hm5_any_test_Mix001_2023_10_4_0-128:1.0000>
wd-v1-3-full: <lora:hm5_any_test_Mix001_2023_10_4_0-128:0.9995>
SweetParfait: <lora:hm5_any_test_Mix001_2023_10_4_0-128:0.9995>
petitcutie_v20: <lora:hm5_any_test_Mix001_2023_10_4_0-128:1.0000>
anyloraCheckpoint_bakedvaeBlessedFp16: <lora:hm5_any_test_Mix001_2023_10_4_0-128:0.9937>

**Comment by tfernd** [comment]
Can you show your config YAML?
Just tested here with 2 models and I get:

```
RealCartoon-Anime - v5: <lora:my cool model_0-128:-0.2810> <lora:my cool model_1-128:0.1119>
Aniverse - THX Ed. (1.4): <lora:my cool model_0-128:-0.2878> <lora:my cool model_1-128:0.0358>
hellokid2d (chibi,cute) - v1.5: <lora:my cool model_0-128:1.0000> <lora:my cool model_1-128:0.0581>
helloYoung2D - v1.0h: <lora:my cool model_0-128:-0.1444> <lora:my cool model_1-128:-1.0576>
```

The formatting is way different.
Try with these options

```
iterations: 6
ranks: 
  - 128
  - 128
```

**Comment by katyukuki** [comment]
The config YAML file I've set up is configured like this.
Thank you. I'll give the suggested settings a try

```
name: hm5_any_test_Mix001_2023_10_4 # how you 

 want your models to be called

models:
  # Specify the paths to your SD 1.5 models in SAFETENSORS formata

  - I:\new_waifu_2023_09_03\Models\StableDiffusion\v1-5-pruned.ckpt
  - I:\new_waifu_2023_09_03\Models\StableDiffusion\wd-v1-3-full.ckpt
  - I:\new_waifu_2023_09_03\Models\StableDiffusion\SweetParfait.safetensors
  - I:\new_waifu_2023_09_03\Models\StableDiffusion\petitcutie_v20.safetensors
  - I:\new_waifu_2023_09_03\Models\StableDiffusion\anyloraCheckpoint_bakedvaeBlessedFp16.safetensors

device: cuda # Choose 'cuda' for GPU acceleration (not recommended for CPU)
dtype: float16 # Use 'float16' for better performance (or 'bfloat16' for RTX 3xxx/4xxx series); 'float32' is slower

iterations: 6 # Number of optimization iterations; should be greater than 2; early stops if it converges

ranks: # Specify the ranks for the LoRA model
  - 128
#  - 64
#  - 32
#  - 16

```

**Comment by katyukuki** [comment]
Yesterday's bug where the weights became the same has been resolved. Thank you. However, there was something I misunderstood because I didn't know how to use it. When I used a different model for the hypermodel-specific 'lora', there was an effect, but normally, this 'lora' is used with the hypermodel, right? At the moment, when using the hypermodel alone, it was either completely black or noisy. I tried the settings from the other day with the generated 'lora', but only a faint figure appeared. I thought maybe my computer was malfunctioning, so I tried generating with another regular model, and the image was generated and working. When installing hypermerge, is there anything needed other than what's written in the manual?

**Comment by tfernd** [comment]
I haven't extensively tested the code with different dtypes outside bfloat16, or checking if some NaN is occuring in the weights. I'll add this (one day). I plan on changing a few things to make the merge more flexible. Unfortunately, for now, I cannot do much. There are so many variables at play that is difficult to check for anything.
As a last resort, when doing the hyper-merge, you should see in the terminal the loss.
Is is small? Like 1e-3?

**Comment by katyukuki** [comment]
The error for 'loss' looked something like this.

Optimizing hyper-checkpoint:  12%|#2        | 1/8 [00:25<02:58, 25.44s/it, loss=0.0564]4]     
Optimizing hyper-checkpoint:  12%|#2        | 1/8 [00:26<03:03, 26.28s/it, loss=0.0225]5]                       

``
Creating average checkpoint: 100%|##########| 3/3 [00:07<00:00,  2.42s/it]
2023-10-06 09:53:25,330 - INFO - Filtering average model checkpoint with LoRA related weights...
2023-10-06 09:53:25,334 - INFO - Loading checkpoints with LoRA-related weights...
Loading checkpoints: 100%|##########| 3/3 [00:01<00:00,  2.72it/s]
Creating hyper-LoRAs:   0%|          | 0/2 [00:00<?, ?it/s]2023-10-06 09:53:26,437 - INFO - Initiating hyper-LoRA creation for step=0, rank=128
2023-10-06 09:53:26,473 - INFO - Computing hyper-checkpoint...
Optimizing hyper-checkpoint:  12%|#2        | 1/8 [00:25<02:58, 25.44s/it, loss=0.0564]4]                                                     
Making LoRA: 100%|##########| 350/350 [00:00<00:00, 5385.54it/s]
2023-10-06 09:53:52,239 - INFO - Removing specific directions from checkpoints...
Removing directions: 100%|##########| 3/3 [00:19<00:00,  6.65s/it]t]
Creating hyper-LoRAs:  50%|#####     | 1/2 [00:45<00:45, 45.83s/it]2023-10-06 09:54:12,272 - INFO - Initiating hyper-LoRA creation for step=1, rank=128
2023-10-06 09:54:12,305 - INFO - Computing hyper-checkpoint...
Optimizing hyper-checkpoint:  12%|#2        | 1/8 [00:26<03:03, 26.28s/it, loss=0.0225]5]                                                     
Making LoRA: 100%|##########| 350/350 [00:00<00:00, 2430.53it/s]s]
2023-10-06 09:54:39,012 - INFO - Removing specific directions from checkpoints...
Removing directions: 100%|##########| 3/3 [00:17<00:00,  6.00s/it]t]
Creating hyper-LoRAs: 100%|##########| 2/2 [01:30<00:00, 45.33s/it]
2023-10-06 09:54:57,090 - INFO - SweetParfait: <lora:hm3_any_test_Mix001_2023_10_6_003_float16_0-128:0.9971> <lora:hm3_any_test_Mix001_2023_10_6_003_float16_1-128:0.9966>
petitcutie_v20: <lora:hm3_any_test_Mix001_2023_10_6_003_float16_0-128:1.0000> <lora:hm3_any_test_Mix001_2023_10_6_003_float16_1-128:1.0000>
anyloraCheckpoint_bakedvaeBlessedFp16: <lora:hm3_any_test_Mix001_2023_10_6_003_float16_0-128:0.9956> <lora:hm3_any_test_Mix001_2023_10_6_003_float16_1-128:0.9951>
2023-10-06 09:54:57,090 - INFO - Saving multipliers'...
``

**Comment by tfernd** [comment]
The loss is a bit too high, it should be 10 to 100 times smaller. Maybe that's the problem.
I'll do some more testing one **day** and change a few things. In the meantime, hang in there :)

**Comment by katyukuki** [comment]
I understand. Thank you. I'm looking forward to the updates.

**Comment by Astropulse** [comment]
I'm getting similar issues to this with the hyper loras having weights nearly identical to each other. The end result of the models and weight formulas is also just producing latent noise, and not an actual image. Unsure if this is because I am using ComfyUI instead of a1111, or the merging and extraction not adding up.

**Comment by tfernd** [comment]
Apologies, but I am no longer actively developing this project. I've devised a more effective approach for merging multiple models. At this time, I cannot commit to when I might be able to implement any modifications.
